export const GITHUB_TOKEN_PLACEHOLDER = "GITHUB_TOKEN_PLACEHOLDER";
export const VERCEL_TOKEN_PLACEHOLDER = "VERCEL_TOKEN_PLACEHOLDER";
export const BASE_APP_ID_PLACEHOLDER = "BASE_APP_ID_PLACEHOLDER";
export const TALENT_VERIFICATION_PLACEHOLDER = "TALENT_VERIFICATION_PLACEHOLDER";
export const BASESPLITPAY_CONTRACT_ADDRESS_PLACEHOLDER = "BASESPLITPAY_CONTRACT_ADDRESS_PLACEHOLDER";
export const BUILDER_CODE_PLACEHOLDER = "BUILDER_CODE_PLACEHOLDER";
